export const HOME_ROUTE = '/';
export const LOGIN_ROUTE = '/login';
export const REGISTRATION_ROUTE = '/registration';
export const CATALOG_ROUTE = '/catalog';
export const PROFILE_ROUTE = '/profile';
export const CART_ROUTE = '/cart';
export const ABOUT_US = '/aboutUs';
export const BASE_URL: string = import.meta.env.VITE_CTP_API_URL;
export const PRODUCT_KEY: string = import.meta.env.VITE_CTP_PROJECT_KEY;
